name: "Hello World workflow" 

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "ðŸŽ‰ The job is automatically triggered by a ${{github.event_name}} event."

      - name: "Print current data"
        run: date